# PROPRIEDADES DA PÁGINA
encoding: utf-8
name: PHP-PB
baseurl: "/"
url: http://php-pb.net/
description: Comunidade PHP na Paraíba

permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: 'page:num'

# MENU DE NAVEGAÇÃO
navigation:
- text: início
  url: '/'
- text: Sobre
  url: '/about'
- text: Vagas em aberto
  url: '/jobs'

future: true
show_drafts: true
markdown: kramdown
highlighter: rouge
